apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-gvisor
  namespace: default
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx-gvisor
  template:
    metadata:
      labels:
        app: nginx-gvisor
    spec:
      runtimeClassName: gvisor
      containers:
      - name: nginx
        image: nginx:1.25
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
          requests:
            memory: "64Mi"
            cpu: "50m"

