apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: gvisor-setup
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: gvisor-setup
  template:
    metadata:
      labels:
        name: gvisor-setup
    spec:
      hostPID: true
      containers:
      - name: gvisor-installer
        image: alpine:3.18
        securityContext:
          privileged: true
        volumeMounts:
        - name: etc-containerd
          mountPath: /host/etc/containerd
        - name: usr-local-bin
          mountPath: /host/usr/local/bin
        - name: systemd
          mountPath: /host/run/systemd
        - name: dbus
          mountPath: /host/run/dbus
        command:
        - /bin/sh
        - -c
        - |
          set -ex
          wget -O /host/usr/local/bin/runsc https://storage.googleapis.com/gvisor/releases/release/latest/x86_64/runsc && \
          wget -O /host/usr/local/bin/containerd-shim-runsc-v1 https://storage.googleapis.com/gvisor/releases/release/latest/x86_64/containerd-shim-runsc-v1
          chmod a+rx /host/usr/local/bin/runsc /host/usr/local/bin/containerd-shim-runsc-v1

          #if ! grep -q runsc /etc/containerd/config.toml; then   sed -i "s|\[plugins.\"io.containerd.grpc.v1.cri\".containerd.runtimes\]|[plugins.\"io.containerd.grpc.v1.cri\".containerd.runtimes]\n        [plugins.\"io.containerd.grpc.v1.cri\".containerd.runtimes.runsc]\n          runtime_type = \"io.containerd.runsc.v1\"|g" /etc/containerd/config.toml; fi
          #
          chroot /host /bin/sh -c 'if ! grep -q runsc /etc/containerd/config.toml; then   sed -i "s|\[plugins.\"io.containerd.grpc.v1.cri\".containerd.runtimes\]|[plugins.\"io.containerd.grpc.v1.cri\".containerd.runtimes]\n        [plugins.\"io.containerd.grpc.v1.cri\".containerd.runtimes.runsc]\n          runtime_type = \"io.containerd.runsc.v1\"|g" /etc/containerd/config.toml; fi'
          chroot /host sh -c "systemctl restart containerd"
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            cpu: 100m
            memory: 100Mi
      volumes:
      - name: etc-containerd
        hostPath:
          path: /etc/containerd
      - name: usr-local-bin
        hostPath:
          path: /usr/local/bin
      - name: systemd
        hostPath:
          path: /run/systemd
      - name: dbus
        hostPath:
          path: /run/dbus
      restartPolicy: Always
      tolerations:
      - operator: "Exists"
      nodeSelector:
        kubernetes.io/os: linux

