apiVersion: v1
kind: Pod
metadata:
  name: nginx-gvisor
spec:
  nodeSelector:
    sandbox: "true" # Match the node label
  tolerations:
    - key: "sandbox"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule" # Tolerate the taint
  runtimeClassName: gvisor
  containers:
    - name: nginx
      image: nginx

