apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: service-webhook
webhooks:
  - name: validate.crd.service
    clientConfig:
      url: https://127.0.0.1:9092/validate
      caBundle: "" 
    admissionReviewVersions:
      - v1
      - v1beta1
    failurePolicy: Fail
    matchPolicy: Exact
    matchConditions:
      - name: cce-managed-service
        expression: object.spec.type == "LoadBalancer"
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["services"]
        scope: "*"
    sideEffects: None
    timeoutSeconds: 30

