apiVersion: tf.upbound.io/v1beta1
kind: Workspace
metadata:
  name: example-inline
  annotations:
    crossplane.io/external-name: coolbucket
spec:
  forProvider:
    source: Inline
    module: |
      // Outputs are written to the connection secret.
      resource "random_id" "example" {
        byte_length = 4
      }

      // The google provider and remote state are configured by the provider
      // config - see providerconfig.yaml.
      resource "opentelekomcloud_obs_bucket" "this" {
        bucket = "crossplane-example-${terraform.workspace}-${random_id.example.hex}"
        acl    = "private"
      }
  writeConnectionSecretToRef:
    namespace: default
    name: terraform-workspace-example-inline
