repositories:
  - name: istio
    url: https://istio-release.storage.googleapis.com/charts 
releases:
  - name: istio-base 
    installed: true 
    chart: istio/base 
    namespace: istio-system 
    version: 1.24.0
    set:
      - name: defaultRevision
        value: default
    values:
      - ./istio-base/values.yaml
  - name: istiod 
    installed: true 
    chart: istio/istiod
    namespace: istio-system
    version: 1.24.0
    values:
    - ./istiod/values.yaml
  - name: cni 
    installed: true 
    chart: istio/cni 
    namespace: istio-system 
    version: 1.24.0
    values:
    - ./cni/values.yaml
  - name: ztunnel 
    installed: true 
    chart: istio/ztunnel 
    namespace: istio-system 
    version: 1.24.0
    values:
    - ./ztunnel/values.yaml
  - name: gateway 
    installed: true 
    chart: istio/gateway 
    namespace: istio-system 
    version: 1.24.0
    values:
    - ./gateway/values.yaml
helmDefaults:
    reuseValues: true
    createNamespace: true 
