repositories:
  - name: grafana
    url:  https://grafana.github.io/helm-charts
  - name: prometheus-community 
    url: https://prometheus-community.github.io/helm-charts
releases:
  - name: loki
    installed: false
    chart: grafana/loki
    version: 5.36.0
    namespace: logging
    values:
    - ./charts/loki/values.yaml
    set:
      - name: loki.storage.s3.secretAccessKey
        value: {{ env "LOKI_SK" }}
      - name: loki.storage.s3.accessKeyId
        value: {{ env "LOKI_AK" }}
      - name: loki.storage.bucketNames.chunks
        value: {{ env "LOKI_S3" }}
      - name: loki.storage.bucketNames.ruler
        value: {{ env "LOKI_S3" }}
      - name: loki.storage.bucketNames.admin
        value: {{ env "LOKI_S3" }}
      - name: loki.storage.s3.region
        value: {{ env "LOKI_REGION" }}
      - name: loki.storage.s3.endpoint
        value: {{ env "LOKI_S3_EP" }}
  - name: promtail
    installed: true
    chart: grafana/promtail
    version: 6.15.3
    namespace: logging
    recreatePods: true
    values:
    - ./charts/promtail/values.yaml
  - name: grafana
    installed: true
    chart: grafana/grafana
    version: 6.61.1
    namespace: logging
    values:
    - ./charts/grafana/values.yaml
    set:
      - name: ingress.hosts[0]
        value: {{ requiredEnv "GRAFANA_FQDN" }}
      - name: ingress.tls[0].hosts[0]
        value: {{ requiredEnv "GRAFANA_FQDN" }}
  - name: prometheus-community
    installed: true
    chart: prometheus-community/prometheus
    version: 25.27.0
    namespace: logging
    values:
    - ./charts/p8s/values.yaml
helmDefaults:
    reuseValues: true
    createNamespace: true 
commonLabels:
    stack: observability
