{
 "title": "Custom network monitor",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "NW TX error rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (nodename) (\n  label_replace(\n    rate(node_network_transmit_errs_total[5m]) / rate(node_network_transmit_packets_total[5m]),\n    \"nodename\", \"$1\", \"instance\", \"(.*):\\\\d+\"\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NW TX drop rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (nodename) (\n  label_replace(\n    rate(node_network_transmit_drop_total[5m]) / rate(node_network_transmit_packets_total[5m]),\n    \"nodename\", \"$1\", \"instance\", \"(.*):\\\\d+\"\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NW RX error rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (nodename) (\n  label_replace(\n    rate(node_network_receive_errs_total[5m]) / rate(node_network_receive_packets_total[5m]),\n    \"nodename\", \"$1\", \"instance\", \"(.*):\\\\d+\"\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NW RX drop rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (nodename) (\n  label_replace(\n    rate(node_network_receive_drop_total[5m]) / rate(node_network_receive_packets_total[5m]),\n    \"nodename\", \"$1\", \"instance\", \"(.*):\\\\d+\"\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network TX for nodes on ens3 if",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (nodename) (\n  label_replace(\n    rate(node_network_transmit_bytes_total{device=\"ens3\"}[2m]),\n    \"nodename\", \"$1\", \"instance\", \"(.*):\\\\d+\"\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network RX for nodes on ens3 if",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (nodename) (\n  label_replace(\n    rate(node_network_receive_bytes_total{device=\"ens3\"}[2m]),\n    \"nodename\", \"$1\", \"instance\", \"(.*):\\\\d+\"\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network TX for nodes on ens3 if",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{device=\"ens3\"}[2m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network RX for nodes on ens3 if",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{device=\"ens3\"}[2m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network TX for nodes on TUNNEL if",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (nodename) (\n  label_replace(\n    rate(node_network_transmit_bytes_total{device=~\"gw_.*\"}[2m]),\n    \"nodename\", \"$1\", \"instance\", \"(.*):\\\\d+\"\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network RX for nodes on TUNNEL if",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (nodename) (\n  label_replace(\n    rate(node_network_receive_bytes_total{device=~\"gw_.*\"}[2m]),\n    \"nodename\", \"$1\", \"instance\", \"(.*):\\\\d+\"\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network TX for nodes on TUNNEL if",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{device=~\"gw_.*\"}[2m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network RX for nodes on TUNNEL if",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{device=~\"gw_.*\"}[2m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}